# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [72]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [73]:
print(np.__version__)
print(np.show_config())

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Astro/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Astro/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Astro/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Astro/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Astro/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Astro/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Astro/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Astro/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [7]:
arr=np.array([25,34,5])
print(arr.size)
print(arr.itemsize)

3
4


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [11]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [13]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [14]:
print(arr[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [15]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [18]:
arr=np.array([1,2,0,0,4,0])
print(arr.nonzero())

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [21]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [22]:
print(np.random.random(3*3*3))

[0.16347852 0.05921872 0.03487055 0.43534129 0.74438908 0.44346831
 0.44753309 0.34639167 0.4181419  0.98426242 0.48638727 0.22569643
 0.8921472  0.98283891 0.36899045 0.56083228 0.41830683 0.11119218
 0.5220647  0.83927364 0.26791954 0.02604402 0.91324412 0.74906861
 0.63135576 0.74992891 0.08441488]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [27]:

arr=np.random.random((10,10))
print(arr)
print(arr.min())
print(arr.max())

[[0.65542881 0.07115059 0.47050052 0.59620072 0.12688103 0.16408502
  0.77183377 0.77437178 0.88070116 0.51129871]
 [0.6323928  0.88181741 0.66982564 0.7009427  0.39395565 0.96441223
  0.00904986 0.17823828 0.36011307 0.89690263]
 [0.14053884 0.78688741 0.37730927 0.97153634 0.27575787 0.46550801
  0.20469286 0.06811544 0.19578854 0.4417417 ]
 [0.4332392  0.28088285 0.85574279 0.18494444 0.48876272 0.98637988
  0.74320301 0.11669104 0.26779465 0.56720115]
 [0.18935705 0.67418516 0.6565632  0.99148788 0.35894715 0.44768369
  0.22384742 0.62877043 0.68450594 0.340327  ]
 [0.5689001  0.63375286 0.02820969 0.16952429 0.40022363 0.80253656
  0.86742656 0.91360584 0.4643193  0.76268845]
 [0.75947527 0.73701657 0.44583428 0.4130723  0.58668543 0.30409487
  0.83402123 0.11869066 0.56708202 0.93438346]
 [0.4295959  0.58789864 0.22007663 0.41465885 0.57088482 0.38115136
  0.56462923 0.56439073 0.08026057 0.83625075]
 [0.96174958 0.90602447 0.73034817 0.41358444 0.56625172 0.29813429
  0.0809869 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [31]:
arr=np.random.random(30)
print(np.mean(arr))

0.5182543497022698


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [34]:
a=np.ones((4,4))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [39]:
a=np.ones((3,3))
b=np.pad(a,pad_width=1,constant_values=0)
print(b)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [43]:
nan,False,False,nan,False

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [53]:
a=np.diag(1+np.arange(4),k=-1)
print(a)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [55]:
a=np.zeros((8,8))
a[1::2,::2]=1
a[::2,1::2]=1
print(a)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [75]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [58]:
a=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [60]:
a=np.random.random((5,5))
b=(a-np.mean(a)/np.std(a))
print(b)

[[-0.99532494 -1.48581639 -1.93575113 -1.5996516  -1.51172236]
 [-1.21767088 -1.5077772  -1.5434862  -1.54474003 -1.37907788]
 [-1.5527092  -1.63731483 -1.4350715  -1.92783801 -1.65799638]
 [-1.74226247 -0.99101603 -1.29259074 -1.12277564 -1.29663042]
 [-1.01146796 -1.63119108 -1.70444383 -1.67174131 -1.39303816]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [66]:

clr=np.dtype([("r",np.ubyte),
                ("g",np.ubyte),
                ("b",np.ubyte),
                ("a",np.ubyte)])
print(clr)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [67]:
a=np.dot(np.ones((5,3)),np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [71]:
arr=np.arange(11)
print(arr)
arr[(3 <= arr) & (arr < 8)] *=-1
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
10
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Legal
Legal
Legal
Legal
Legal
Illegal

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [77]:
nan
0
[-2.14748365e+09]

nan
0
[-2.14748365e+09]


C:\Users\Astro\AppData\Local\Temp/ipykernel_31164/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Astro\AppData\Local\Temp/ipykernel_31164/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [86]:
a=np.random.uniform(-6,4,6)
print(a)
print(np.copysign(np.ceil(np.abs(a)),a))

[-5.95777036  0.91712029  3.52405668  3.26938817 -2.94805851 -0.36464624]
[-6.  1.  4.  4. -3. -1.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [88]:
a1=np.random.randint(0,10,10)
a2=np.random.randint(0,10,20)
print(np.intersect1d(a1,a2))

[0 1 2 5 6 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [91]:
warn=np.seterr(all='ignore')
a=np.ones(1)/0
_=np.seterr(**warn)
with np.errstate(all='ignore'):
    np.arange(3)/0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False expression

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [92]:
yesterday=np.datetime64('today')-np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today')+np.timedelta64(1)
print(yesterday,today,tomorrow)

2022-04-02 2022-04-03 2022-04-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [93]:
date=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(date)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [6]:

A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [14]:
a=np.random.uniform(2,10,10)
print(a%1)
print(np.floor(a))
print(np.ceil(a))
print(a.astype(int))
print(np.trunc(a))

[0.74945078 0.26799775 0.93122769 0.48138483 0.25125557 0.39413455
 0.01454087 0.05168645 0.09207112 0.4470719 ]
[6. 8. 5. 8. 4. 5. 9. 9. 4. 2.]
[ 7.  9.  6.  9.  5.  6. 10. 10.  5.  3.]
[6 8 5 8 4 5 9 9 4 2]
[6. 8. 5. 8. 4. 5. 9. 9. 4. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [16]:
a=np.zeros((5,5))
a = a+ np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [18]:
def generate():
    for x in range(10):
        yield x
a=np.fromiter(generate(),dtype=int,count=-1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [20]:
a=np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [22]:
a=np.random.random(10)
print(a)
a.sort()
print(a)

[0.57961591 0.47553002 0.02646927 0.81123315 0.27600191 0.13215536
 0.43926136 0.54383029 0.54859012 0.58808356]
[0.02646927 0.13215536 0.27600191 0.43926136 0.47553002 0.54383029
 0.54859012 0.57961591 0.58808356 0.81123315]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [24]:
a=np.arange(10)
print(a)
np.add.reduce(a)

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [26]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
c=np.allclose(A,B)
print(c)
d=np.array_equal(A,B)
print(d)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [28]:
a=np.zeros(10)
a.flags.writeable=False
a[0]=1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [30]:
a=np.random.random((10,2))
x,y=a[:,0],a[:,1]
print(x)
print(y)
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[0.60773906 0.05265922 0.52253393 0.38881704 0.26266409 0.16384416
 0.65308404 0.21950924 0.63737758 0.04787631]
[0.76607488 0.03539088 0.40295861 0.27999556 0.09310191 0.5778779
 0.28054793 0.54687645 0.21347804 0.79689784]
[0.97786373 0.06344689 0.65986161 0.47914111 0.27867614 0.60065612
 0.71079245 0.58928614 0.67217785 0.79833471]
[0.90014462 0.59173657 0.65690815 0.62410315 0.34063576 1.29451977
 0.40573848 1.18909461 0.32318852 1.5107901 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [32]:
a=np.random.random(10)
print(a)
a[a.argmax()]=0
print(a)


[0.73290277 0.38213261 0.7196161  0.99646573 0.48285748 0.91459892
 0.41460753 0.03487301 0.85433218 0.15525626]
[0.73290277 0.38213261 0.7196161  0.         0.48285748 0.91459892
 0.41460753 0.03487301 0.85433218 0.15525626]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [34]:
a=np.zeros((5,5),[('x',float),('y',float)])
a['x'],a['y']=np.meshgrid(np.linspace(0,1,5),
                          np.linspace(0,1,5))
print(a)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [40]:
x=np.linspace(10,12,6)
y=np.linspace(4,8,6)
c=1.0 / np.subtract.outer(x,y)
print(c)

[[0.16666667 0.19230769 0.22727273 0.27777778 0.35714286 0.5       ]
 [0.15625    0.17857143 0.20833333 0.25       0.3125     0.41666667]
 [0.14705882 0.16666667 0.19230769 0.22727273 0.27777778 0.35714286]
 [0.13888889 0.15625    0.17857143 0.20833333 0.25       0.3125    ]
 [0.13157895 0.14705882 0.16666667 0.19230769 0.22727273 0.27777778]
 [0.125      0.13888889 0.15625    0.17857143 0.20833333 0.25      ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [41]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [47]:

a=np.arange(50)
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [52]:
a=np.arange(50)
v=np.random.uniform(1,20)
print(a)
print(v)
ind=(np.abs(a-v)).argmin()
print(a[ind])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
15.613001157713523
16


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [57]:
a=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Astro\AppData\Local\Temp/ipykernel_37468/3068233936.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [58]:
a=np.random.random((10,2))
x,y=np.atleast_2d(a[:,0],a[:,1])
d=np.sqrt((x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.33656582 0.66654666 0.24674718 0.67390545 0.78644104
  0.37937546 0.75721575 0.06489931 0.50087698]
 [0.33656582 0.         0.7137122  0.41655256 0.69931611 0.81054917
  0.3711917  0.78068307 0.40068913 0.77267103]
 [0.66654666 0.7137122  0.         0.42189887 0.04488701 0.12241636
  0.3440387  0.09600691 0.66572122 0.51439772]
 [0.24674718 0.41655256 0.42189887 0.         0.43271914 0.54309379
  0.19744248 0.51446162 0.24460441 0.36561534]
 [0.67390545 0.69931611 0.04488701 0.43271914 0.         0.11491172
  0.33404053 0.08473276 0.67732338 0.55203044]
 [0.78644104 0.81054917 0.12241636 0.54309379 0.11491172 0.
  0.44815161 0.03028504 0.78734763 0.61823699]
 [0.37937546 0.3711917  0.3440387  0.19744248 0.33404053 0.44815161
  0.         0.41788122 0.40437019 0.52404234]
 [0.75721575 0.78068307 0.09600691 0.51446162 0.08473276 0.03028504
  0.41788122 0.         0.75889207 0.60113722]
 [0.06489931 0.40068913 0.66572122 0.24460441 0.67732338 0.78734763
  0.40437019 0.75889

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [67]:
a=(np.random.rand(10)*100).astype(np.float32)
print(a)
b=a.view(np.int32)
b[:]=a
print(b)


[94.539314  22.766214  21.934015   1.2922791 74.35287   61.902756
 78.87703   28.467413   6.287594  91.51448  ]
[94 22 21  1 74 61 78 28  6 91]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [68]:
from io import StringIO
s=StringIO('''1, 2, 3, 4, 5
              6,  ,  , 7, 8
               ,  , 9,10,11''')
a=np.genfromtxt(s,delimiter=",",dtype=np.int)

print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\Astro\AppData\Local\Temp/ipykernel_37468/2614472639.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.genfromtxt(s,delimiter=",",dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [73]:
a=np.arange(4).reshape(2,2)
for i,v in np.ndenumerate(a):
    print(i,v)
for i in np.ndindex(a.shape):
    print(i,a[i])
    

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [75]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d=np.sqrt(x*x+y*y)
sigma,mu=1.0,0.0
g=np.exp(-((d-mu)**2 / (2.0* sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [77]:
n=10
p=3
a=np.zeros((n,n))
np.put(a,np.random.choice(range(n*n),p,replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [78]:
a=np.random.rand(5,10)
b=a - a.mean(axis=1,keepdims=True)
print(y)

[[-1.         -1.         -1.         -1.         -1.         -1.
  -1.         -1.         -1.         -1.        ]
 [-0.77777778 -0.77777778 -0.77777778 -0.77777778 -0.77777778 -0.77777778
  -0.77777778 -0.77777778 -0.77777778 -0.77777778]
 [-0.55555556 -0.55555556 -0.55555556 -0.55555556 -0.55555556 -0.55555556
  -0.55555556 -0.55555556 -0.55555556 -0.55555556]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333
  -0.33333333 -0.33333333 -0.33333333 -0.33333333]
 [-0.11111111 -0.11111111 -0.11111111 -0.11111111 -0.11111111 -0.11111111
  -0.11111111 -0.11111111 -0.11111111 -0.11111111]
 [ 0.11111111  0.11111111  0.11111111  0.11111111  0.11111111  0.11111111
   0.11111111  0.11111111  0.11111111  0.11111111]
 [ 0.33333333  0.33333333  0.33333333  0.33333333  0.33333333  0.33333333
   0.33333333  0.33333333  0.33333333  0.33333333]
 [ 0.55555556  0.55555556  0.55555556  0.55555556  0.55555556  0.55555556
   0.55555556  0.55555556  0.55555556  0.55555556]
 [ 0.777

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [79]:
a=np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[2 2 3]
 [1 0 9]
 [4 7 3]]
[[1 0 9]
 [2 2 3]
 [4 7 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [84]:
a=np.random.randint(0,3,(3,3))
print(a)
print((~a.any(axis=0)).any())

[[2 2 0]
 [2 0 2]
 [0 0 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [86]:
a=np.random.uniform(0,1,10)
b=0.5
print(a)
m=a.flat[np.abs(a-b).argmin()]
print(m)

[0.01933768 0.59366133 0.04373596 0.82663926 0.60105488 0.05975359
 0.94486096 0.30549415 0.08394614 0.4265595 ]
0.4265595009166391


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [97]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
print(a)
print(b)
itr=np.nditer([a,b,None])
for x,y,z in itr: z[...] = x + y
print(itr.operands[2])
    

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [99]:
class namarr(np.ndarray):
    def __new__(cls,array,name="no name"):
        obj=np.asarray(array).view(cls)
        obj.name=name
        return obj
    def __array_final__(self,obj):
        if obj is None: return
        self.into=getattr(obj,'name',"no name")

a=namarr(np.arange(10),"range_10")
print(a.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [102]:
a=np.ones(10)
print(a)
b=np.random.randint(0,len(a),10)
a += np.bincount(b,minlength=len(a))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 3. 2. 2. 1. 1. 3. 1. 3. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [103]:
a=[1,2,3,4,5,6]
b=[1,3,9,3,4,1]
c=np.bincount(b,a)
print(c)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [108]:
w, h = 256, 256
b = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
color = np.unique(b.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [109]:
a=np.random.randint(0,10,(3,4,3,4))
s=a.sum(axis=(-2,-1))
print(s)

[[60 47 59 58]
 [44 70 34 38]
 [57 51 49 45]]



#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [110]:
a=np.random.uniform(0,1,100)
b=np.random.randint(0,10,100)
d_sums=np.bincount(b,weights=a)
d_count=np.bincount(b)
d_mean=d_sums/d_count
print(d_mean)

[0.42687935 0.4853453  0.62556434 0.43961112 0.4600828  0.62446575
 0.55086864 0.42237374 0.48581207 0.5356438 ]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [111]:
a=np.random.uniform(0,1,(5,5))
b=np.random.uniform(0,1,(5,5))
np.diag(np.dot(a,b))


array([0.84899449, 0.85377621, 0.82086717, 1.97384658, 1.29015459])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [113]:
a = np.array([1,2,3,4,5])
b = 3
c = np.zeros(len(a) + (len(a)-1)*(b))
c[::b+1] = a
print(c)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [114]:
a=np.ones((5,5,3))
b=3*np.ones((5,5))
print(a*b[:,:,None])

[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [115]:
a=np.arange(16).reshape(4,4)
print(a)
a[[0,1]]=a[[1,0]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [120]:
faces = np.random.randint(0,100,(10,3))
print(faces)
v = np.roll(faces.repeat(2,axis=1),-1,axis=1)
v = v.reshape(len(v)*3,2)
v = np.sort(v,axis=1)
print(v)
s = v.view( dtype=[('p0',v.dtype),('p1',v.dtype)] )
s = np.unique(s)
print(s)

[[27 63 92]
 [75 64  0]
 [55 57 23]
 [94 39 51]
 [94  0  3]
 [37 31  2]
 [90 19 48]
 [92 57 42]
 [ 6 92 58]
 [94 35 50]]
[[27 63]
 [63 92]
 [27 92]
 [64 75]
 [ 0 64]
 [ 0 75]
 [55 57]
 [23 57]
 [23 55]
 [39 94]
 [39 51]
 [51 94]
 [ 0 94]
 [ 0  3]
 [ 3 94]
 [31 37]
 [ 2 31]
 [ 2 37]
 [19 90]
 [19 48]
 [48 90]
 [57 92]
 [42 57]
 [42 92]
 [ 6 92]
 [58 92]
 [ 6 58]
 [35 94]
 [35 50]
 [50 94]]
[( 0,  3) ( 0, 64) ( 0, 75) ( 0, 94) ( 2, 31) ( 2, 37) ( 3, 94) ( 6, 58)
 ( 6, 92) (19, 48) (19, 90) (23, 55) (23, 57) (27, 63) (27, 92) (31, 37)
 (35, 50) (35, 94) (39, 51) (39, 94) (42, 57) (42, 92) (48, 90) (50, 94)
 (51, 94) (55, 57) (57, 92) (58, 92) (63, 92) (64, 75)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [122]:
a=np.bincount([1,1,2,3,3,4,4,6])
c=np.repeat(np.arange(len(a)),a)
print(c)

[1 1 2 3 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [123]:
def avg(a,n=4):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n -1:] / n

c=np.arange(10)
print(avg(c,n=4))

[1.5 2.5 3.5 4.5 5.5 6.5 7.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [126]:
from numpy.lib import stride_tricks

def fn(a,n):
    shape=(a.size - n+1, n)
    strides=(a.strides[0],a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)                            

c=fn(np.arange(10),3)
print(c)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [129]:
a=np.random.randint(0,1,7)
print(a)
b=np.logical_not(a,out=a)
print(b)
c=np.random.uniform(-1.0,10.0,8)
print(c)
d=np.negative(c,out=c)
print(d)

[0 0 0 0 0 0 0]
[1 1 1 1 1 1 1]
[0.64138783 5.00697595 9.5478892  3.19269045 5.94733088 5.7388364
 8.02786371 2.05992806]
[-0.64138783 -5.00697595 -9.5478892  -3.19269045 -5.94733088 -5.7388364
 -8.02786371 -2.05992806]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [132]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-1,10,(10,2))
P1 = np.random.uniform(-1,10,(10,2))
p  = np.random.uniform(-1,10,(10,2))
print(distance(P0, P1, p))

[1.94917912 0.44833545 1.28953699 1.90641892 1.91243369 5.96498252
 2.79013169 4.69826665 2.16956145 1.23588811]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [134]:
P0 = np.random.uniform(-1,10,(10,2))
P1 = np.random.uniform(-1,10,(10,2))
p  = np.random.uniform(-1,10,(10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[5.16076725 3.55146351 7.8753457  4.69894842 5.06506308 0.70095614
  2.79918828 3.48245435 0.03556877 8.07392395]
 [0.52557052 2.57110823 5.55995299 2.68924275 5.8041462  6.09049153
  1.28262254 1.98910592 3.24716742 0.91190107]
 [7.88701451 5.73933308 1.50007644 1.55132912 0.85679671 6.2786196
  3.55708164 6.44669426 4.78851658 8.43113268]
 [1.48496328 3.18496121 9.36637697 0.18476829 9.05057523 2.42355398
  4.99842749 3.10344242 5.58355147 1.42856168]
 [5.42595706 4.00691021 9.68475014 6.56409922 6.29609225 1.40552797
  4.47996655 3.66012626 0.53394178 9.10723201]
 [2.75988263 0.92296676 6.46289885 1.1908812  5.05368849 3.4506523
  1.74737443 1.19206052 1.16578736 4.8712524 ]
 [3.8551228  1.99281236 5.81321305 1.6347101  4.09640252 3.60721566
  1.00266729 2.29584058 0.06817248 5.80040188]
 [2.74063314 4.67693727 7.45343365 3.06892819 8.17124911 5.14196703
  3.33715617 4.24783799 5.71316162 0.72906231]
 [3.4261759  1.94405459 9.7751009  4.77429351 7.22886836 0.49648677
  4.80266854 1

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [135]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 3 7 2 5 2 1 3 4 3]
 [0 2 7 7 3 2 8 4 1 8]
 [1 0 1 7 7 6 6 4 0 1]
 [5 3 8 4 3 8 1 0 5 7]
 [4 6 3 5 6 8 3 2 3 9]
 [7 2 8 3 8 4 5 8 1 2]
 [8 4 9 9 3 3 7 5 8 6]
 [3 4 6 5 0 0 4 1 1 9]
 [5 4 6 7 2 5 4 7 7 4]
 [0 6 0 3 8 2 7 7 1 8]]
[[0 0 0 0 0]
 [0 8 3 7 2]
 [0 0 2 7 7]
 [0 1 0 1 7]
 [0 5 3 8 4]]


C:\Users\Astro\AppData\Local\Temp/ipykernel_37468/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [140]:
a=np.arange(1,15,dtype=np.uint32)
print(a)
b=stride_tricks.as_strided(a,(11,4),(4,4))
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [143]:
a = np.random.randint(0,10,(5,5))
print(a)
U, S, V = np.linalg.svd(a)
rank = np.linalg.matrix_rank(a)
print(rank)

[[5 7 3 1 0]
 [2 1 4 4 6]
 [8 0 7 1 6]
 [0 9 8 0 6]
 [0 1 8 2 4]]
5


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [146]:
a=np.random.randint(1,5,20)
print(a)
print(np.bincount(a).argmax())

[4 3 1 3 2 2 2 3 3 4 3 4 4 3 4 1 4 1 1 4]
4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [149]:
a = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (a.shape[0]-3)
j = 1 + (a.shape[1]-3)
C = stride_tricks.as_strided(a, shape=(i, j, n, n), strides=a.strides + a.strides)
print(C)

[[[[4 4 2]
   [2 3 1]
   [1 4 3]]

  [[4 2 2]
   [3 1 1]
   [4 3 3]]

  [[2 2 2]
   [1 1 4]
   [3 3 2]]

  [[2 2 3]
   [1 4 3]
   [3 2 1]]

  [[2 3 1]
   [4 3 1]
   [2 1 1]]

  [[3 1 1]
   [3 1 3]
   [1 1 3]]

  [[1 1 1]
   [1 3 4]
   [1 3 1]]

  [[1 1 0]
   [3 4 1]
   [3 1 2]]]


 [[[2 3 1]
   [1 4 3]
   [2 2 3]]

  [[3 1 1]
   [4 3 3]
   [2 3 2]]

  [[1 1 4]
   [3 3 2]
   [3 2 3]]

  [[1 4 3]
   [3 2 1]
   [2 3 4]]

  [[4 3 1]
   [2 1 1]
   [3 4 3]]

  [[3 1 3]
   [1 1 3]
   [4 3 2]]

  [[1 3 4]
   [1 3 1]
   [3 2 4]]

  [[3 4 1]
   [3 1 2]
   [2 4 2]]]


 [[[1 4 3]
   [2 2 3]
   [1 1 0]]

  [[4 3 3]
   [2 3 2]
   [1 0 2]]

  [[3 3 2]
   [3 2 3]
   [0 2 4]]

  [[3 2 1]
   [2 3 4]
   [2 4 2]]

  [[2 1 1]
   [3 4 3]
   [4 2 3]]

  [[1 1 3]
   [4 3 2]
   [2 3 2]]

  [[1 3 1]
   [3 2 4]
   [3 2 2]]

  [[3 1 2]
   [2 4 2]
   [2 2 0]]]


 [[[2 2 3]
   [1 1 0]
   [1 1 3]]

  [[2 3 2]
   [1 0 2]
   [1 3 3]]

  [[3 2 3]
   [0 2 4]
   [3 3 3]]

  [[2 3 4]
   [2 4 2]
   [3 3 3]]

  [[3 4 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [150]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5  9 10 11 14]
 [ 9  0  5 10 14]
 [10  5  6 42 15]
 [11 10 42  8  4]
 [14 14 15  4  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [152]:
p,n=10,20
a=np.ones((p,n,n))
b=np.ones((p,n,1))
c=np.tensordot(a,b,axes=[[0,2],[0,1]])
print(c)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [156]:
a = np.ones((16,16))
n = 4
S = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], n), axis=0),
                                       np.arange(0, a.shape[1], n), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [157]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [158]:
a=np.arange(1000)

np.random.shuffle(a)
print(a)
n=10
print(a[np.argsort(a)[-n:]])

[719 374 872 174 653 630 199 197 730 152 904 941 139 557  32 631  25 575
 316 739 674 177 349 165 613 922 368  86 433 772 652 992 513 838 308 551
 870 869 150 737 788 298 304 145 851 407 845  40 231 744 731 156  12 168
 644 769 132 136 315 113 391 994 125 542 808 849 782 444 108 494 510 608
 951  27 692 437 717 211 961  97 679  48 454 947 266 722 160 779 173 663
  36 907 373 292 518 664 424 924  91 967 280 733 497 382 595 585 223 143
 724 190 274 346 323 468 989 565  60 117 541 639 271 700 745 216 944 568
 979 363 517 935 179 453 795 221 707 680  56 180  83 375 859 439 233 499
 104 303 351 939 887 345 343 378 620 781 503 699 550  54 668 154 642 147
 959 172 609 114 425 816 427  82 661 101 847 380 842 770 646 415 984 670
 436 790 119 229 633 259 701 296 796 711  64 196 901 902 434 976 116 414
 511 534  55 659  98 785 760 570 214 886  18 548 681 279  59 392 222 389
 805 928 189 402 369 577 487 938 621 539 417 287 182 798 527 890 945 875
 974 540 726  14 352 405 807 804 366 412 317 794 78

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [160]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([4, 5, 7], [0,1], [2,3])))

[[4 0 2]
 [4 0 3]
 [4 1 2]
 [4 1 3]
 [5 0 2]
 [5 0 3]
 [5 1 2]
 [5 1 3]
 [7 0 2]
 [7 0 3]
 [7 1 2]
 [7 1 3]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [167]:
a= np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
b= np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(b)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:

a=np.random.rand(int(1e2))
print(np.power(x,3))
print(x*x*x)
print(np.einsum('i,i,i->i',x,x,x))


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [5]:

A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
c=(A[..., np.newaxis, np.newaxis]== B)
row=np.where(c.any((3,1)).all(1))[0]
print(row)

[3]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [6]:
a=np.random.randint(0,5,(10,3))
print(a)
E=np.all(a[:,1:] == a[:,:-1],axis=1)
b=a[~E]
print(b)
uneq=a[a.max(axis=1) != a.min(axis=1),:]
print(uneq)

[[1 0 1]
 [4 3 1]
 [4 0 3]
 [1 1 1]
 [4 3 3]
 [4 4 4]
 [4 1 0]
 [3 1 3]
 [4 1 3]
 [2 4 4]]
[[1 0 1]
 [4 3 1]
 [4 0 3]
 [4 3 3]
 [4 1 0]
 [3 1 3]
 [4 1 3]
 [2 4 4]]
[[1 0 1]
 [4 3 1]
 [4 0 3]
 [4 3 3]
 [4 1 0]
 [3 1 3]
 [4 1 3]
 [2 4 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [9]:
mat=np.array([0,1,2,4,7,16,32,64,128,256],dtype=np.uint8)
print(np.unpackbits(mat[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [12]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [14]:
A=np.random.uniform(0,1,10)
B=np.random.uniform(0,1,10)
print('sum',np.einsum('i->', A))     
print('A*B',np.einsum('i,i->i', A, B))
print('inner',np.einsum('i,i', A, B))   
print('outer',np.einsum('i,j->ij', A, B))  

sum 5.255527113221135
A*B [0.41967536 0.28175042 0.05230144 0.53721359 0.16775128 0.62069371
 0.05195727 0.35016664 0.08583611 0.08371746]
inner 2.6510632759979895
outer [[0.41967536 0.35349738 0.29050868 0.48242225 0.19922644 0.69942744
  0.11716921 0.63363073 0.1194272  0.09015109]
 [0.3344967  0.28175042 0.23154611 0.38450828 0.15879081 0.5574694
  0.09338817 0.50502701 0.09518788 0.07185373]
 [0.07555583 0.06364154 0.05230144 0.0868524  0.03586753 0.12592071
  0.02109444 0.11407507 0.02150096 0.01623026]
 [0.46734019 0.39364602 0.32350335 0.53721359 0.22185368 0.77886525
  0.13047676 0.70559564 0.13299121 0.10039004]
 [0.35337216 0.29764944 0.24461213 0.40620587 0.16775128 0.5889271
  0.09865801 0.5335254  0.10055928 0.0759084 ]
 [0.37243299 0.3137046  0.25780646 0.42811654 0.17679976 0.62069371
  0.10397961 0.56230366 0.10598342 0.08000288]
 [0.18609997 0.15675414 0.12882257 0.21392432 0.08834456 0.31015265
  0.05195727 0.28097589 0.05295855 0.03997641]
 [0.23192737 0.19535509 0.1

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [16]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)
print(r_int)
print(x_int)
print(y_int)

[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [22]:
a = np.asarray([[1.5, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [2.5, 3.5, 1.1, 0.0]])
n = 4
b = np.logical_and.reduce(np.mod(a, 1) == 0, axis=-1)
b &= (a.sum(axis=-1) == n)
print(a[b])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [23]:
a=np.random.randn(100)
n=1000
idx=np.random.randint(0,a.size,(n,a.size))
mean=a[idx].mean(axis=1)
comper=np.percentile(mean,[10,98.5])
print(comper)

[-0.33176599  0.05233996]
